## Deep Neural Network (Multilayer perceptron (MLP))

<span>A neural network with 1 hidden layer (3 units): </span>
<img src="NN.png">

<span> Algorithm used: </span>
<img src="MLP-algo.png">

In [1]:
import numpy as np

In [2]:
class NeuralNetwork:
    def __init__(self):
        # parametrs
        self.inputSize = 2
        self.hiddenSize = 4
        self.outputSize = 1
        
        # weights
        self.W1 = np.random.rand(self.inputSize,self.hiddenSize)
        # print('W1 = ',self.W1)
        self.W2 = np.random.rand(self.hiddenSize,self.outputSize)
        # print('W2 = ',self.W2)
        
        # bias
        self.B1 = np.random.rand(self.hiddenSize,1)
        # print('B1 = ',self.B1)
        self.B2 = np.random.rand(self.outputSize,1)
        # print('B2 = ',self.B2)
    
    
    def sigmoid(self,Z):
        return 1 / (1 + np.exp((-1) * Z))
    
    
    def dev_sigmoid(self,Z):
        return Z * (1 - Z)
    
    
    def forwardPropagation(self,X):
        self.z1 = np.dot(X,self.W1) + self.B1.T
        # print("z1 = ",self.z1)
        self.a1 = self.sigmoid(self.z1)
        # print("a1 = ",self.a1)
        
        self.z2 = np.dot(self.a1,self.W2) + self.B2.T
        # print("z2= ",self.z2)
        self.a2 = self.sigmoid(self.z2)
        # print("a2= ",self.a2)
        
        return self.a2
        
    
    def backwardPropagation(self,X,y):
        self.a2_error = self.a2 - y
        # print("a2_error= ",self.a2_error)
        self.a2_delta = self.dev_sigmoid(self.a2) * self.a2_error
        # print("a2_delta= ",self.a2_delta)
        
        self.a1_error = np.dot(self.a2_delta,self.W2.T)
        # print("a1_error= ",self.a1_error)
        self.a1_delta = self.dev_sigmoid(self.a1) * self.a1_error
        # print("z1_delta= ",self.z1_delta)
        
        self.W2 -= np.dot(self.a1.T,self.a2_delta)
        self.W1 -= np.dot(X.T,self.a1_delta)
        
        
    def train(self,X,y):
        y_pred = self.forwardPropagation(X)
        self.backwardPropagation(X,y)
        return y_pred

In [3]:
# AND

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[0],[0],[1]])

nn = NeuralNetwork()

for i in range(4000):
    y_pred = nn.train(X,y)

print(np.round(y_pred))

[[0.]
 [0.]
 [0.]
 [1.]]


In [4]:
# OR

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[1]])

nn = NeuralNetwork()

for i in range(4000):
    y_pred = nn.train(X,y)

print(np.round(y_pred))

[[0.]
 [1.]
 [1.]
 [1.]]


In [5]:
# XOR

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

nn = NeuralNetwork()

for i in range(4000):
    y_pred = nn.train(X,y)

print(np.round(y_pred))

[[0.]
 [1.]
 [1.]
 [0.]]


In [6]:
# NXOR

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[1],[0],[0],[1]])

nn = NeuralNetwork()

for i in range(4000):
    y_pred = nn.train(X,y)

print(np.round(y_pred))

[[1.]
 [0.]
 [0.]
 [1.]]
